# Generated by Django 5.1.2 on 2024-10-19 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='combined_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='combinedRule',
            fields=[
                ('combined_rule_id', models.AutoField(primary_key=True, serialize=False)),
                ('rule_string', models.TextField()),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combined_rules', to='new_app.rule')),
            ],
        ),
    ]
